apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: default
  annotations:
    expose.neverup.at/subdomain: "test"
    expose.neverup.at/ports: "80/tcp"
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
